### ISSUE TITLE
Some comments on the revised version

### ISSUE THREAD

**Issue by ohsOllila** [davesmith4398/best_practice_membranes#7]
I have now red also the revised version with great interest. I have listed here some comments which came to my mind. Hopefully you find these useful.

1) Page 3:
"For a detailed view of thermal fluctuations and the role of entropy"
has been removed from page 3. Simulations can give very
detailed information about fluctuations and entropy which
are experimentally hard to access. Therefore, I think that
this would be one of the key instances were simulations can
give real added value. Thus, I would keep this point in the
manuscript.

2) Page 3:
"When the expected  mesostructure of a lipid solution is  not
a planar bilayer but  otherwise unclear"
There are also other mesotructures than planar bilayer which can
be well characterized by experiments and continuum theories, like
hexagonal phases etc. However, if the mesostructure is something
else than well known phase, like here http://dx.doi.org/10.1021/la404684r,
the simulations can be useful. The sentence could be
modified accordingly.

3) The list of example scientific questions has been added to page 3.
I think that all these questions can be better answered experimentally
than with current simulations, except these 

- Whatis the activation  barrier and rate of  membrane pore formation  and closure?
- How does lipid leaflet  number  asymmetry relate  to  membrane  curvature?
- What is a reasonable bending modulus to plug into a continuum theoretical simulation of a complex, multicomponent membrane?
- How does phase  separation facilitate morphological transformations in  lipid  vesicles?

It would be more useful to list practical examples with references where simulations
give some solid and novel information which is not accessible with other techniques.

4) 3.3 Preparation of initial configurations
"Lamellar lipid bilayers exist for a variety of concentrations
of water to lipid ratios. All force fields
will  produce  single bilayers if conditions are
at full hydration (30 waters per lipid) or an order higher  above."
Large number of experimental conditions produce multilamellar phase.
Most simulation systems are too small for the formation of real multilamellar phase.
Therefore, it is not clear if simulations would form multilamellar,
which they should, or a single bilayer. This sentence should
be reformulated. Now it gives an impression that simulations have
an artefact that they do not form multilamellar phases.
We do not know if there is or not such artefact (if known, please cite).

5) Figure 1: Green and blue are very difficult to distinguish in the bottom.

6) Page 8:
"As shown in “Statistical  mechanics
 of  inhomogeneous fluids”[114] by Schofield and Henderson,
 section IV,  observables that can be  cast  as resulting from a
 global deformation of the system can  be computed unambiguously
 from the  profile, including  curvature  derivatives (see  Sodt
 2016[119], supplemental). Care  must be taken,  however, to
 interpret local  features of the profile qualitatively.  For example,
 it is appropriate to ask the  question “Does  the  model capture
 the  qualitative structure of  the competing forces in lipid bilayer
 assembly and stability"
This is quite technical and difficult to understand. I think that
it would be better to clearly say that there is some potential
ambiguity in the definition without too much details and cite
appropriate publications for more details.

7) Page 9:
"Computing error bars is tricky, but the order_parameters
tool in LOOS [107] offers one approach"
There is also one option presented in http://dx.doi.org/10.1021/acs.jpcb.5b04878

8) Page 9:
"Since the area per lipid and NMR order parameter are tightly coupled"
would be better as:
"Since the area per lipid and NMR order parameter of acyl chains are coupled"

9) Page 9:
"Calculated metrics can be compared with other simulations
and directly with quadrupolar NMR splitting experiments [90]"
would be better as
"Calculated metrics can be compared with other simulations
and directly with quadrupolar or dipolar NMR splitting experiments [90]"

10) Figure 3:
It is not clear if these are values from simulations or experiments,
and if from simulations, how realistic these are when compared to experiments.

11) Page 10, left column:
State of the art comparison of bilayer dimensions, like area per molecule and
thickness, to experiments is made using scattering forms factors, see e.g. http://dx.doi.org/10.1016/j.bbamem.2016.01.019
and references therein. I think that inclusion of form factors to the discussion
would be highly relevant. Only the less accurate comparisons using lipid volume and
order parameters are currently discussed. 

12) Table 1:
Different atomistic force fields have very different qualities for the
headgroup and glycerol backbone structure (http://dx.doi.org/10.1021/acs.jpcb.5b04878)
and cation binding affinity (http://dx.doi.org/10.1039/C6CP04883H).
These informations should be included in the table.
Some people also compare diffusion coefficients (http://www.cgmartini.nl/index.php/blog/269-jungle2,
http://dx.doi.org/10.1021/acs.jpcb.6b01870)

13) Page 15:
For the discussion about polarizable models, it could be interesting
that the implicit inclusion of polarizability improves
cation binding affinity to PC lipid bilayers: http://dx.doi.org/10.1021/acs.jpcb.7b12510

14) Page 21:
"NMRlipids is a particularly new and comprehensive initiative launched by  S.
 Ollila to  compare  membrane properties  across  13 different
 force fields"
 The goal of the NMRlipids project is to
 "understand the atomistic resolution structures of lipid bilayers"
 (http://nmrlipids.blogspot.com/p/about.html).
 In the first publication there happens to be 13 models, however,
 the goal is not compare these but find the best possible models.

**Comment by davesmith4398** [comment]
Dear Samuli,

Per the editor's recommendation, we also include our response in-line below.

Sincerely,

Dave

==

<<I have now red also the revised version with great interest. I have listed here some comments which came to my mind. Hopefully you find these useful.

Page 3:
"For a detailed view of thermal fluctuations and the role of entropy"
has been removed from page 3. Simulations can give very
detailed information about fluctuations and entropy which
are experimentally hard to access. Therefore, I think that
this would be one of the key instances were simulations can
give real added value. Thus, I would keep this point in the
manuscript.>>

We have made the requested change.

<<Page 3:
"When the expected mesostructure of a lipid solution is not
a planar bilayer but otherwise unclear"
There are also other mesotructures than planar bilayer which can
be well characterized by experiments and continuum theories, like
hexagonal phases etc. However, if the mesostructure is something
else than well known phase, like here http://dx.doi.org/10.1021/la404684r,
the simulations can be useful. The sentence could be
modified accordingly.>>

We have made the requested change.

<<The list of example scientific questions has been added to page 3.
I think that all these questions can be better answered experimentally
than with current simulations, except these
Whatis the activation barrier and rate of membrane pore formation and closure?
How does lipid leaflet number asymmetry relate to membrane curvature?
What is a reasonable bending modulus to plug into a continuum theoretical simulation of a complex, multicomponent membrane?
How does phase separation facilitate morphological transformations in lipid vesicles?
It would be more useful to list practical examples with references where simulations
give some solid and novel information which is not accessible with other techniques.>>

We have separated the original list of questions into (1) those that, currently, can only be answered by simulations and (2) those where simulations can supplement experiment. As these are all general questions, we do not feel that we need references for these, and will not pursue practical examples at this time.

<<3.3 Preparation of initial configurations
"Lamellar lipid bilayers exist for a variety of concentrations
of water to lipid ratios. All force fields
will produce single bilayers if conditions are
at full hydration (30 waters per lipid) or an order higher above."
Large number of experimental conditions produce multilamellar phase.
Most simulation systems are too small for the formation of real multilamellar phase.
Therefore, it is not clear if simulations would form multilamellar,
which they should, or a single bilayer. This sentence should
be reformulated. Now it gives an impression that simulations have
an artefact that they do not form multilamellar phases.
We do not know if there is or not such artefact (if known, please cite).>>

As the community currently does not have a robust test for the formation of multiple layers in all-atom systems, for the time being, we have simply removed the word “single” from this text in the article.

<<Figure 1: Green and blue are very difficult to distinguish in the bottom.>>

Green and blue are fairly standard color variations in figures, and are rarely indistinguishable for potential readers with color blindness. Furthermore, we are already using several colors to illustrate the four-region model. For these reasons, we are prone to keep the current color scheme. 

<<Page 8:
"As shown in “Statistical mechanics
of inhomogeneous fluids”[114] by Schofield and Henderson,
section IV, observables that can be cast as resulting from a
global deformation of the system can be computed unambiguously
from the profile, including curvature derivatives (see Sodt
2016[119], supplemental). Care must be taken, however, to
interpret local features of the profile qualitatively. For example,
it is appropriate to ask the question “Does the model capture
the qualitative structure of the competing forces in lipid bilayer
assembly and stability"
This is quite technical and difficult to understand. I think that
it would be better to clearly say that there is some potential
ambiguity in the definition without too much details and cite
appropriate publications for more details.>>

For a guide to best practices it is important to warn simulators about potentially bad practices – interpreting ambiguous features quantitatively. As a topic of current interest this caution could be revised in the future, a nice feature of a living journal!

<<Page 9:
"Computing error bars is tricky, but the order_parameters
tool in LOOS [107] offers one approach"
There is also one option presented in http://dx.doi.org/10.1021/acs.jpcb.5b04878>>

We have added a sentence and reference for this error calculation approach as well.

<<Page 9:
"Since the area per lipid and NMR order parameter are tightly coupled"
would be better as:
"Since the area per lipid and NMR order parameter of acyl chains are coupled">>

We have made the requested change.

<<Page 9:
"Calculated metrics can be compared with other simulations
and directly with quadrupolar NMR splitting experiments [90]"
would be better as
"Calculated metrics can be compared with other simulations
and directly with quadrupolar or dipolar NMR splitting experiments [90]">>

We have made the requested change.

<<Figure 3:
It is not clear if these are values from simulations or experiments,
and if from simulations, how realistic these are when compared to experiments.>>

These values are reported from simulation (see Boughter et al.) We have added in the caption that these are from simulation. These are reasonable compared to experiment (see Boughter et al.); we don’t feel the need to state this in our current manuscript.

<<Page 10, left column:
State of the art comparison of bilayer dimensions, like area per molecule and
thickness, to experiments is made using scattering forms factors, see e.g. http://dx.doi.org/10.1016/j.bbamem.2016.01.019
and references therein. I think that inclusion of form factors to the discussion
would be highly relevant. Only the less accurate comparisons using lipid volume and
order parameters are currently discussed.>>

We have added some form factor discussion at the conclusion of Section 3.4.4.

<<Table 1:
Different atomistic force fields have very different qualities for the
headgroup and glycerol backbone structure (http://dx.doi.org/10.1021/acs.jpcb.5b04878)
and cation binding affinity (http://dx.doi.org/10.1039/C6CP04883H).
These informations should be included in the table.
Some people also compare diffusion coefficients (http://www.cgmartini.nl/index.php/blog/269-jungle2,
http://dx.doi.org/10.1021/acs.jpcb.6b01870)>>

We respectfully decline to include this information at this time. We did add some of this and related material in the last round of reviews. Due to the system size dependence of diffusivity estimates, we think that the diffusivity is poorly suited for the discussion of force fields and model selection. For a more detailed discussion of the structural considerations, we refer to your extensive progress with the NMRlipids project.

<<Page 15:
For the discussion about polarizable models, it could be interesting
that the implicit inclusion of polarizability improves
cation binding affinity to PC lipid bilayers: http://dx.doi.org/10.1021/acs.jpcb.7b12510>>

We thank the reviewer for this helpful suggestion, and have added some discussion to the paragraph on polarizable models.

<<Page 21:
"NMRlipids is a particularly new and comprehensive initiative launched by S.
Ollila to compare membrane properties across 13 different
force fields"
The goal of the NMRlipids project is to
"understand the atomistic resolution structures of lipid bilayers"
(http://nmrlipids.blogspot.com/p/about.html).
In the first publication there happens to be 13 models, however,
the goal is not compare these but find the best possible models.>>

We have clarified our description of NMRlipids and moved it to the discussion of NMR order parameters in Section 3.4.4, where we believe that it is better suited.

**Comment by davidlmobley** [comment]
If you all have made these changes, you could close this issue. Leaving it open makes it look like this is unresolved.

**Comment by davesmith4398** [comment]
Thanks, David. We will close this out.
